### ISSUE TITLE
Upgrade Design ?

### ISSUE THREAD

**Issue by SulivanM** [TannicArcher/Unterweltmafia#3]
IHello !
I have a question, its possible to update the design to a new design like :

[www.unterweltmafia.de](http://www.unterweltmafia.de/)

[www.unterweltkoenig.de](http://www.unterweltkoenig.de/)

**Comment by TannicArcher** [comment]
> IHello ! I have a question, its possible to update the design to a new design like :
> 
> [www.unterweltmafia.de](http://www.unterweltmafia.de/)
> 
> [www.unterweltkoenig.de](http://www.unterweltkoenig.de/)


yes, maybe I just think there is no longer PHP version 5.4, but most likely 8 and the design is new, so if there is a script for this, I will definitely update it
